# https://taskfile.dev

version: '3'

vars:
  NODE_MACS: '1c:69:7a:6a:bd:10, 1c:69:7a:6a:b9:2d, 1c:69:7a:6a:8a:e8'
  NODE_IPS: '10.3.0.101, 10.3.0.102, 10.3.0.103'
  #NODE_MACS: '1c:69:7a:6a:bd:10'
  #NODE_IPS: '10.3.0.101'
  LOCAL_IP: 
    sh: ip addr | grep 'state UP' -A2 | tail -n1 | awk '{print $2}' | cut -f1  -d'/' | xargs


tasks:
  run-pixiecore:talos:
    silent: true
    cmds:
      - sudo iptables -I nixos-fw -p udp -m multiport --dports 67,69,4011 -j ACCEPT
      - sudo iptables -I nixos-fw -p tcp -m multiport --dports 80,8081,64172 -j ACCEPT
      - echo "LOCAL_IP={{.LOCAL_IP}}" > .env
      - docker compose up -d talos-config pixiecore

  boot:
    silent: true
    cmds:
      - for: { var: NODE_MACS, split: ', '}
        cmd: wakeonlan {{ .ITEM }}

  cleanup:
    silent: true
    cmds:
      - docker compose down
      - rm .env
      - sudo iptables -D nixos-fw -p udp -m multiport --dports 67,69,4011 -j ACCEPT
      - sudo iptables -D nixos-fw -p tcp -m multiport --dports 80,8081,64172 -j ACCEPT
